visio/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
  url ('^$', views.home, name="home"),
  url(r'^performances', views.performances, name="performances"),
  url(r'^login', views.login, name="login"),
]

visioAdmin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
# from django.urls import path
# from django.views.generic.base import TemplateView
import debug_toolbar
from visio import views


urlpatterns = [
    url(r'^visio/', include(('visio.urls', 'visio'), namespace='visio')),
    url(r'^$', views.performances, name="performances"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

visio/models.py
from django.db import models
from django.db.models.expressions import F

class Drv(models.Model):
  name = models.CharField('drv', max_length=16, unique=True)

  class Meta:
    verbose_name = "DRV"

  def __str__(self) ->str:
    return self.name

class Agent(models.Model):
  name = models.CharField('agent', max_length=64, unique=True)
  drv = models.ForeignKey('drv', on_delete=models.PROTECT, blank=False)

  class Meta:
    verbose_name = "Agent"

  def __str__(self) ->str:
    return self.name

class AgentFinitions(models.Model):
  name = models.CharField('agent_finitions', max_length=64, unique=True)
  drv = models.ForeignKey('drv', on_delete=models.PROTECT, blank=False)

  class Meta:
    verbose_name = "Agent Finitions"

  def __str__(self) ->str:
    return self.name

class Dep(models.Model):
  name = models.CharField('dep', max_length=2, unique=True)

  class Meta:
    verbose_name = "Département"

  def __str__(self) ->str:
    return self.name

class Bassin(models.Model):
  name = models.CharField('bassin', max_length=64, unique=True)

  class Meta:
    verbose_name = "Bassin"

  def __str__(self) ->str:
    return self.name

class Ville(models.Model):
  name = models.CharField('ville', max_length=128, unique=True)

  class Meta:
    verbose_name = "Ville"

  def __str__(self) ->str:
    return self.name

class SegmentMarketing(models.Model):
  name = models.CharField('segment_marketing', max_length=32, unique=True)

  class Meta:
    verbose_name = "Segment Marketing"

  def __str__(self) ->str:
    return self.name

class SegmentCommercial(models.Model):
  name = models.CharField('segment_commercial', max_length=16, unique=True)

  class Meta:
    verbose_name = "Segment Commercial"

  def __str__(self) ->str:
    return self.name

class Enseigne(models.Model):
  name = models.CharField('name', max_length=64, unique=True, blank=False, default="Inconnu")

  class Meta:
    verbose_name = "Enseigne"

  def __str__(self) ->str:
    return self.name

class Ensemble(models.Model):
  name = models.CharField('name', max_length=64, unique=True, blank=False, default="Inconnu")
  enseigne = models.ForeignKey('enseigne', on_delete=models.PROTECT, blank=False, default=7)

  class Meta:
    verbose_name = "Ensemble"

  def __str__(self) ->str:
    return self.name

class SousEnsemble(models.Model):
  name = models.CharField('name', max_length=64, unique=True, blank=False, default="Inconnu")

  class Meta:
    verbose_name = "Sous-Ensemble"

  def __str__(self) ->str:
    return self.name

class Site(models.Model):
  name = models.CharField('name', max_length=64, unique=True, blank=False, default="Inconnu")

  class Meta:
    verbose_name = "Site"

  def __str__(self) ->str:
    return self.name

class Pdv(models.Model):
  code = models.CharField('PDV code', max_length=10, blank=False, default="Inconnu")
  name = models.CharField('PDV', max_length=64, blank=False, default="Inconnu")
  drv = models.ForeignKey('drv', on_delete=models.PROTECT,  blank=False)
  agent = models.ForeignKey('agent', on_delete=models.PROTECT, blank=False)
  dep = models.ForeignKey("dep", on_delete=models.PROTECT, blank=False)
  bassin = models.ForeignKey("bassin", on_delete=models.PROTECT, blank=False)
  ville = models.ForeignKey("ville", on_delete=models.PROTECT, blank=False)
  latitude = models.FloatField('Latitude', unique=False, blank=False, default=0.0)
  longitude = models.FloatField('Longitude', unique=False, blank=False, default=0.0)
  segment_commercial = models.ForeignKey("segmentcommercial", on_delete=models.PROTECT, blank=False, default=1)
  segment_marketing = models.ForeignKey("segmentmarketing", on_delete=models.PROTECT, blank=False, default=1)
  enseigne = models.ForeignKey('enseigne', on_delete=models.PROTECT, blank=False, default=7)
  ensemble = models.ForeignKey('ensemble', on_delete=models.PROTECT, blank=False, default=43)
  sous_ensemble = models.ForeignKey('sousensemble', on_delete=models.PROTECT, blank=False, default=1)
  site = models.ForeignKey('site', on_delete=models.PROTECT, blank=False, default=1)
  available = models.BooleanField(default=True)
  sale = models.BooleanField("Ne vend pas de plaque", default=True)
  redistributed = models.BooleanField("Redistribué", default=True)
  redistributedEnduit = models.BooleanField("redistribué Enduit", default=True)
  pointFeu = models.BooleanField('Point Feu', default=False)
  closedAt = models.DateTimeField('Date de Fermeture', blank=True, null=True, default=None)

  class Meta:
    verbose_name = "Point de Vente"

  def __str__(self) ->str:
    return self.name + " " + self.code



# Modèles pour l'AD

class Produit(models.Model):
  name = models.CharField('name', max_length=32, unique=True, blank=False, default="Inconnu")

  class Meta:
    verbose_name = "Produit"

  def __str__(self) ->str:
    return self.name

class Industrie(models.Model):
  name = models.CharField('name', max_length=32, unique=True, blank=False, default="Inconnu")

  class Meta:
    verbose_name = "Industrie"

  def __str__(self) ->str:
    return self.name

class Ventes(models.Model):
  date = models.DateTimeField('Date de Saisie', blank=True, null=True, default=None)
  pdv = models.ForeignKey("PDV", on_delete=models.CASCADE, blank=False, default=1)
  industry = models.ForeignKey("Industrie", on_delete=models.PROTECT, blank=False, default=17)
  product = models.ForeignKey("Produit", on_delete=models.CASCADE, blank=False, default=6)
  volume = models.FloatField('Volume', unique=False, blank=True, default=0.0)

  class Meta:
    verbose_name = "Ventes"
    unique_together = ('pdv', 'industry', 'product')

  def __str__(self) ->str:
    return str(self.pdv) + " " + str(self.industry) + " " + str(self.product)

visio/views.py
from sys import prefix
from django.shortcuts import render
from django.http import HttpResponse
from rest_framework.response import Response
from django.http import JsonResponse
from django.shortcuts import redirect
from django.contrib import auth
from visio.dataModel.manageFromOldDatabase import manageFromOldDatabase
from visio.dataModel.tableModel import tablePdv, tableVentes
from visio.dataModel.readXlsx import ReadXlsxRef, ReadXlsxVentes

def home(request):
  if request.user.is_authenticated:
    return redirect('/visio/performances/')
  return redirect('/visio/login/')

def performances(request):
  context = {}
  if request.method == 'GET' and 'action' in request.GET:
    if request.GET['action'] == 'disconnect':
      auth.logout(request)
    else:
      return JsonResponse(performancesAction(request.GET['action'], request.GET))
  elif request.method == 'POST' and request.POST.get('login') == "Se connecter":
    HtlmPage = performancesLogin(request)
    if HtlmPage: return HtlmPage
  if request.user.is_authenticated:
    context['userName'] = request.user.username
    return render(request, 'visio/performances.html', context)
  return redirect('/visio/login/')

def performancesLogin(request):
  userName = request.POST.get('userName')
  password = request.POST.get('password')
  user = auth.authenticate(username=userName, password=password)
  if user == None:
    context = {'userName': userName, 'password':password, 'message':"Le couple login password n'est pas conforme"}
    return render(request, 'visio/login.html', context)
  else:
    context = {"userName":'', 'password':''}
    auth.login(request, user)

def performancesAction(action, get):
  if action == "perfEmptyBase":
    return manageFromOldDatabase.emptyDatabase(get['start'] == 'true')
  elif action == "perfPopulateBase":
    if get['method'] == 'empty':
      return manageFromOldDatabase.emptyDatabase(get['start'] == 'true')
    else:
      return manageFromOldDatabase.populateDatabase(get['start'] == 'true', method=get['method'])
  elif action == "perfImportPdv":
    return tablePdv.json if tablePdv else {'titles':[], 'values':[], 'tableIndex':[]}
  elif action == "perfImportPdvSave":
    print("importPdv")
    dataXlsx = ReadXlsxRef("ReferentielVisio_V2_FI - 202101", tablePdv)
    if dataXlsx.errors:
      return {"errors":dataXlsx.errors}
    return dataXlsx.json
  elif action == "perfImportVentes":
    return tableVentes.json if tableVentes else {'titles':[], 'values':[], 'tableIndex':[]}
  elif action == "perfImportVentesSave":
    dataXlsx = ReadXlsxVentes("Volume_Visio_06_2021", tableVentes)
    return dataXlsx.json if dataXlsx else {'titles':[], 'values':[], 'tableIndex':[]}
  else:
    return {'titles':[], 'values':[], 'tableIndex':[]}

def login(request):
  return render(request, 'visio/login.html')

visio/templates/visio/base.html
<html  lang="fr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'visio/images/header.ico' %}" type="image/x-icon">
    <title>Visio Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,700;1,100;1,300;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'visio/css/general.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'visio/css/performances.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'visio/css/dataTable.css' %}" />
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css" /> -->
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'visio/js/main.js' %}"></script>
  <script charset="utf8" src="{% static 'visio/js/dataTable.min.js' %}"></script>
  <!-- <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script> -->

</html>

visio/templates/visio/login.html
<!DOCTYPE html>
<html lang="fr">
  <head>

    {% load static %}
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'visio/images/header.ico' %}" type="image/x-icon">
    <title>Visio Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,300;0,400;0,700;1,100;1,300;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'visio/css/general.css' %}" />

    
    <body class="backgroundImage">
      <section class="loginSection">
        <article class="loginArticle">
          <h1 class="colorSiniat">Visio Admin</h1>
          <form class="loginBox" method=post action="{% url 'visio:performances' %}" accept-charset="utf-8">
            {% csrf_token %}
            <div class="loginInput">
              <img class="iconStandard" src= "{% static 'visio/images/user.png' %}" alt="speudo" title="Entrer votre pseudo"/>
              <input class="loginInput" name="userName" type=text placeholder="Saisir votre pseudo" value="{{ userName }}"></input>
            </div>
            <div class="loginInput">
              <img class="iconStandard" src= "{% static 'visio/images/password.png' %}" alt="speudo" title="Entrer votre pseudo"/>
              <input class="loginInput" name="password" type=password placeholder="Saisir votre mot de passe"></input>
            </div>
            <input class="loginButton" type="submit" name="login" value="Se connecter"></input>
            <p class="loginMessage">{{ message }}</p>
        </article>
      </section>
      <img class="logo" src="{% static 'visio/images/logoAppli.png' %}" alt="Logo Visio" title="Logo Visio"/>
    </body>

visio/templates/visio/performances.html
{% extends 'visio/base.html' %}
<!-- {% load static %} -->

{% block content %}
  <aside class="dataLogin">
    <p>{{ userName }}</p>
    <form method=get action="{% url 'visio:performances' %}">
      {% csrf_token %}
      <input type="submit" name="action" value="disconnect"/>
    </form>
  </aside>
  <header>
    <div class="loader"></div>
  </header>
  <main class="performancesMain">
    <nav class="performancesNav">
      <p>Performances</p>
      {% csrf_token %}
      <button id="PerfEmtpyBase" class="buttonNav">Vider la base de données</button>
      <button id="PerfPopulateBase" class="buttonNav">Remplir la base de données</button>
      <button id="VisualizePdv" class="buttonNav">Visualiser le référentiel</button>
      <button id="VisualizePdvXlsx" class="buttonNav">Visualiser le nouveau référentiel</button>
      <button id="VisualizeVentes" class="buttonNav">Visualiser les Ventes Siniat</button>
      <button id="VisualizeVentesXlsx" class="buttonNav">Visualiser les nouvelles Ventes Siniat</button>
      <button id="ManageUser" class="buttonNav">Gestion des utilisateurs</button>
    </nav>
    <section>
    </section>
    <div id="marginRight"></div>
  </main>
{% endblock %}